version: "3"
services:
  spbstu:
    image: spbstu:latest
    restart: on-failure
    environment:
      - SPRING_APPLICATION_NAME=spbstu
      - WAIT_HOSTS=mysql:3306
      - WAIT_HOSTS_TIMEOUT=500
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    networks:
      - eureka_network
      - common_network
      - redis_link
    depends_on:
      - redis
    ports:
      - "8071:8071"
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass aw4cha3vaith

    volumes:
      - "redis-data:/var/lib/redis"
      - "redis-conf:/usr/local/etc/redis/redis.conf"
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - redis_link
    ports:
      - "6379:6379"

volumes:
  redis-data:
  redis-conf:

networks:
  redis_link:
  common_network:
    name: common_network
    external: true
  eureka_network:
    name: eureka_network
    external: true